/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AppFunilRouteImport } from './routes/_app/funil'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'
import { Route as AppOrcamentosRouteImport } from './routes/_app/orcamentos'
import { Route as AppServicosRouteImport } from './routes/_app/servicos'
import { Route as AppImoveisIndexRouteImport } from './routes/_app/imoveis.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/funil': typeof AppFunilRoute
  '/inicio': typeof AppInicioRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/servicos': typeof AppServicosRoute
  '/imoveis/': typeof AppImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/funil': typeof AppFunilRoute
  '/inicio': typeof AppInicioRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/servicos': typeof AppServicosRoute
  '/imoveis': typeof AppImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_app/funil': typeof AppFunilRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/servicos': typeof AppServicosRoute
  '/_app/imoveis/': typeof AppImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/funil'
    | '/inicio'
    | '/orcamentos'
    | '/servicos'
    | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/funil'
    | '/inicio'
    | '/orcamentos'
    | '/servicos'
    | '/imoveis'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/entrar'
    | '/_app/funil'
    | '/_app/inicio'
    | '/_app/orcamentos'
    | '/_app/servicos'
    | '/_app/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/funil': {
      id: '/_app/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/imoveis/': {
      id: '/_app/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppFunilRoute: typeof AppFunilRoute
  AppInicioRoute: typeof AppInicioRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppServicosRoute: typeof AppServicosRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFunilRoute: AppFunilRoute,
  AppInicioRoute: AppInicioRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppServicosRoute: AppServicosRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
