/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AppAdministracaoRouteImport } from './routes/_app/administracao'
import { Route as AppFunilRouteImport } from './routes/_app/funil'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'
import { Route as AppProspeccaoRouteImport } from './routes/_app/prospeccao'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes.index'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'
import { Route as AppContratosIndexRouteImport } from './routes/_app/contratos.index'
import { Route as AppContratosIdRouteImport } from './routes/_app/contratos.$id'
import { Route as AppImoveisIndexRouteImport } from './routes/_app/imoveis.index'
import { Route as AppImoveisIdRouteImport } from './routes/_app/imoveis.$id'
import { Route as AppMedicaoIndexRouteImport } from './routes/_app/medicao.index'
import { Route as AppMedicaoIdRouteImport } from './routes/_app/medicao.$id'
import { Route as AppOportunidadesIdRouteImport } from './routes/_app/oportunidades.$id'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app/orcamentos.index'
import { Route as AppOrcamentosIdRouteImport } from './routes/_app/orcamentos.$id'
import { Route as AppServicosIndexRouteImport } from './routes/_app/servicos.index'
import { Route as AppServicosIdRouteImport } from './routes/_app/servicos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdministracaoRoute = AppAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProspeccaoRoute = AppProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContratosIdRoute = AppContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMedicaoIndexRoute = AppMedicaoIndexRouteImport.update({
  id: '/medicao/',
  path: '/medicao/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMedicaoIdRoute = AppMedicaoIdRouteImport.update({
  id: '/medicao/$id',
  path: '/medicao/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOportunidadesIdRoute = AppOportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrcamentosIdRoute = AppOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicosIndexRoute = AppServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicosIdRoute = AppServicosIdRouteImport.update({
  id: '/servicos/$id',
  path: '/servicos/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/administracao': typeof AppAdministracaoRoute
  '/funil': typeof AppFunilRoute
  '/inicio': typeof AppInicioRoute
  '/prospeccao': typeof AppProspeccaoRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/imoveis/$id': typeof AppImoveisIdRoute
  '/medicao/$id': typeof AppMedicaoIdRoute
  '/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/servicos/$id': typeof AppServicosIdRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/imoveis/': typeof AppImoveisIndexRoute
  '/medicao/': typeof AppMedicaoIndexRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
  '/servicos/': typeof AppServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/administracao': typeof AppAdministracaoRoute
  '/funil': typeof AppFunilRoute
  '/inicio': typeof AppInicioRoute
  '/prospeccao': typeof AppProspeccaoRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/imoveis/$id': typeof AppImoveisIdRoute
  '/medicao/$id': typeof AppMedicaoIdRoute
  '/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/servicos/$id': typeof AppServicosIdRoute
  '/clientes': typeof AppClientesIndexRoute
  '/contratos': typeof AppContratosIndexRoute
  '/imoveis': typeof AppImoveisIndexRoute
  '/medicao': typeof AppMedicaoIndexRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
  '/servicos': typeof AppServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/_app/administracao': typeof AppAdministracaoRoute
  '/_app/funil': typeof AppFunilRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/prospeccao': typeof AppProspeccaoRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/contratos/$id': typeof AppContratosIdRoute
  '/_app/imoveis/$id': typeof AppImoveisIdRoute
  '/_app/medicao/$id': typeof AppMedicaoIdRoute
  '/_app/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/_app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/_app/servicos/$id': typeof AppServicosIdRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/imoveis/': typeof AppImoveisIndexRoute
  '/_app/medicao/': typeof AppMedicaoIndexRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/_app/servicos/': typeof AppServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/entrar'
    | '/administracao'
    | '/funil'
    | '/inicio'
    | '/prospeccao'
    | '/clientes/$id'
    | '/contratos/$id'
    | '/imoveis/$id'
    | '/medicao/$id'
    | '/oportunidades/$id'
    | '/orcamentos/$id'
    | '/servicos/$id'
    | '/clientes/'
    | '/contratos/'
    | '/imoveis/'
    | '/medicao/'
    | '/orcamentos/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/entrar'
    | '/administracao'
    | '/funil'
    | '/inicio'
    | '/prospeccao'
    | '/clientes/$id'
    | '/contratos/$id'
    | '/imoveis/$id'
    | '/medicao/$id'
    | '/oportunidades/$id'
    | '/orcamentos/$id'
    | '/servicos/$id'
    | '/clientes'
    | '/contratos'
    | '/imoveis'
    | '/medicao'
    | '/orcamentos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/design-system'
    | '/entrar'
    | '/_app/administracao'
    | '/_app/funil'
    | '/_app/inicio'
    | '/_app/prospeccao'
    | '/_app/clientes/$id'
    | '/_app/contratos/$id'
    | '/_app/imoveis/$id'
    | '/_app/medicao/$id'
    | '/_app/oportunidades/$id'
    | '/_app/orcamentos/$id'
    | '/_app/servicos/$id'
    | '/_app/clientes/'
    | '/_app/contratos/'
    | '/_app/imoveis/'
    | '/_app/medicao/'
    | '/_app/orcamentos/'
    | '/_app/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/administracao': {
      id: '/_app/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AppAdministracaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/funil': {
      id: '/_app/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prospeccao': {
      id: '/_app/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AppProspeccaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contratos/$id': {
      id: '/_app/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AppContratosIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/imoveis/': {
      id: '/_app/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/imoveis/$id': {
      id: '/_app/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/medicao/': {
      id: '/_app/medicao/'
      path: '/medicao'
      fullPath: '/medicao/'
      preLoaderRoute: typeof AppMedicaoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/medicao/$id': {
      id: '/_app/medicao/$id'
      path: '/medicao/$id'
      fullPath: '/medicao/$id'
      preLoaderRoute: typeof AppMedicaoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/oportunidades/$id': {
      id: '/_app/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof AppOportunidadesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orcamentos/$id': {
      id: '/_app/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AppOrcamentosIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servicos/': {
      id: '/_app/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof AppServicosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servicos/$id': {
      id: '/_app/servicos/$id'
      path: '/servicos/$id'
      fullPath: '/servicos/$id'
      preLoaderRoute: typeof AppServicosIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdministracaoRoute: typeof AppAdministracaoRoute
  AppFunilRoute: typeof AppFunilRoute
  AppInicioRoute: typeof AppInicioRoute
  AppProspeccaoRoute: typeof AppProspeccaoRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppContratosIdRoute: typeof AppContratosIdRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
  AppMedicaoIdRoute: typeof AppMedicaoIdRoute
  AppOportunidadesIdRoute: typeof AppOportunidadesIdRoute
  AppOrcamentosIdRoute: typeof AppOrcamentosIdRoute
  AppServicosIdRoute: typeof AppServicosIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
  AppMedicaoIndexRoute: typeof AppMedicaoIndexRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
  AppServicosIndexRoute: typeof AppServicosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdministracaoRoute: AppAdministracaoRoute,
  AppFunilRoute: AppFunilRoute,
  AppInicioRoute: AppInicioRoute,
  AppProspeccaoRoute: AppProspeccaoRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppContratosIdRoute: AppContratosIdRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
  AppMedicaoIdRoute: AppMedicaoIdRoute,
  AppOportunidadesIdRoute: AppOportunidadesIdRoute,
  AppOrcamentosIdRoute: AppOrcamentosIdRoute,
  AppServicosIdRoute: AppServicosIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
  AppMedicaoIndexRoute: AppMedicaoIndexRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
  AppServicosIndexRoute: AppServicosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
